
import "./globals.css";

import Navbar from "@/component/navbar";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <head>
      <link href="https://api.fontshare.com/v2/css?f[]=satoshi@500,700&display=swap" rel="stylesheet" />
      </head>
      <body>
        <Navbar />
        {children}

      </body>
    </html>
  );
}
